version: '3'

services:
  epic-auto:
    image: luminoleon/epicgames-claimer:latest
    container_name: epic-auto
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - AUTO_UPDATE=true
      - EMAIL=your_email_address
      - PASSWORD=your_password # 2FA Closed!
      - RUN_AT=23:00 # Run everyday
      - ONCE=false
