version: "3"

services:
  talebook:
    container_name: talebook
    image: talebook/talebook:v3.8.1
    volumes:
      - /data/talebook:/data
    ports:
       - "80:80"
       - "443:443"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      # 调整为『SSR=ON』可开启「服务器端渲染」模式，对于搜索引擎更友好，同时更消耗服务器性能
      - SSR=OFF
    depends_on:
      - douban-rs-api
    restart: always
      
  douban-rs-api:
    container_name: douban-rs-api
    # https://github.com/cxfksword/douban-api-rs
    image: ghcr.io/cxfksword/douban-api-rs:latest
    restart: always
